server:
  port: 10220

eureka:
  client:
    service-url:
      defaultZone: http://kimd0.iptime.org:10210/eureka/  # 유레카 서버 주소
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configs/
#        git:
#          uri: https://github.com/kd2675/server-config.git
#          default-label: master
#          search-paths: configs