spring:
  application:
    name: server-config
  profiles:
    active: local
    group:
      local: local
      test: test
      dev: dev
      prod: prod

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, beans
  endpoint:
    health:
      show-details: always
