server:
  port: 10220

eureka:
  client:
    service-url:
      defaultZone: http://kimd0.iptime.org:10210/eureka/  # 유레카 서버 주소
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: kimd0.iptime.org
    prefer-ip-address: true
    ip-address: ${eureka.instance.hostname}

spring:
  application:
    name: server-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configs/
  #        git:
  #          uri: https://github.com/kd2675/server-config.git
  #          default-label: master
  #          search-paths: configs

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, beans
  endpoint:
    health:
      show-details: always
