spring:
  main:
    web-application-type: reactive
  application:
    name: server-cloud
  profiles:
    active: local
    group:
      local: local
      test: test
      dev: dev
      prod: prod
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
      log-condition-evaluation-delta: false
  cloud:
    gateway:
      # 로드밸런싱 설정
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false  # Ribbon 비활성화, Spring Cloud LoadBalancer 사용

  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: false

server:
  tomcat:
    use-relative-redirects: true
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 86400

jwt:
  secret: testtesttesttesttsttesttesttesttest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    info:
      enabled: true  # ✅ info 엔드포인트 명시적 활성화
    defaults:
      enabled: true
    redis:
      enabled: false  # Redis 헬스체크만 비활성화