spring:
  application:
    name: server-batch
  profiles:
    active: local
    group:
      local: local
      test: test
      dev: dev
      prod: prod
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
      log-condition-evaluation-delta: false
  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    redis:
      enabled: false  # Redis 헬스체크만 비활성화